export const BLOG = {
  GET_COMPLETE: 'GET_COMPLETE',
  GET_BY_KEY_COMPLETE: 'GET_BY_KEY_COMPLETE',
  CHANGE: 'CHANGE',
  REMOVE_BY_KEY: 'REMOVE_BY_KEY',
  REMOVE_BY_KEY_COMPLETE: 'REMOVE_BY_KEY_COMPLETE',
  SAVE_BY_KEY: 'SAVE_BY_KEY',
  SAVE_BY_KEY_COMPLETE: 'SAVE_BY_KEY_COMPLETE'
}
